In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_excel('flight_price.xlsx')

In [7]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [19]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [25]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['month'] =df['Date_of_Journey'].str.split('/').str[1]
df['year'] = df['Date_of_Journey'].str.split('/').str[2]

In [28]:
df['Date']= df['Date'].astype(int)

In [29]:
df['month']= df['month'].astype(int)
df['year'] = df['year'].astype(int)

In [30]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Date                int64
month               int64
year                int64
dtype: object

In [33]:
df.drop('Date_of_Journey', inplace = True, axis =1)

In [34]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Date                int64
month               int64
year                int64
dtype: object

In [36]:
df['Arrival_Time'].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], dtype=object)

In [38]:
df['Arrival_Time'] =df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [42]:
df['Arrival_hour'] =df['Arrival_Time'].str.split(':').str[0]
df['Arrival_minute'] =df['Arrival_Time'].str.split(':').str[1]

In [44]:
df['Arrival_hour'] =df['Arrival_hour'].astype(int)
df['Arrival_minute'] =df['Arrival_minute'].astype(int)

In [51]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Date                int64
month               int64
year                int64
Arrival_hour        int64
Arrival_minute      int64
dep_hour           object
Dep_minute         object
dtype: object

In [46]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [50]:
df['dep_hour'] =df['Dep_Time'].str.split(':').str[0]
df['Dep_minute'] =df['Dep_Time'].str.split(':').str[1]

In [52]:
df['dep_hour'] =df['dep_hour'].astype(int)
df['Dep_minute'] = df['Dep_minute'].astype(int)

In [54]:
df.drop('Dep_Time', axis =1, inplace =True)

In [58]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,month,year,Arrival_hour,Arrival_minute,dep_hour,Dep_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [63]:
df['Total_Stops'].mode()

0    1.0
Name: Total_Stops, dtype: float64

In [62]:
df['Total_Stops'] =df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stop':2,'3 stop':3, '4 stop':0, np.nan:1})

In [64]:
df['Total_Stops']

0        0.0
1        NaN
2        NaN
3        1.0
4        1.0
        ...
10678    0.0
10679    0.0
10680    0.0
10681    0.0
10682    NaN
Name: Total_Stops, Length: 10683, dtype: float64

In [65]:
df.drop('Route', axis =1, inplace=True)

In [66]:
df.dtypes

Airline             object
Source              object
Destination         object
Duration            object
Total_Stops        float64
Additional_Info     object
Price                int64
Date                 int64
month                int64
year                 int64
Arrival_hour         int64
Arrival_minute       int64
dep_hour             int64
Dep_minute           int64
dtype: object

In [70]:
df['Duration_hour'] =df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [71]:
df['Duration_min'] =df['Duration'].str.split(' ').str[0].str.split('h').str[1]

In [74]:
df.drop('Duration_min', axis =1, inplace=True)

In [75]:
df.dtypes

Airline             object
Source              object
Destination         object
Total_Stops        float64
Additional_Info     object
Price                int64
Date                 int64
month                int64
year                 int64
Arrival_hour         int64
Arrival_minute       int64
dep_hour             int64
Dep_minute           int64
Duration_hour       object
dtype: object

In [76]:
from sklearn.preprocessing import OneHotEncoder

In [77]:
encoder = OneHotEncoder()

In [80]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [83]:
df1 =pd.DataFrame(encoder.fit_transform(df[['Airline','Source','Destination']]).toarray(), columns = encoder.get_feature_names_out())

In [85]:
final_df =pd.concat([df.reset_index(drop=True), df1], axis=1)

In [87]:
final_df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'Date', 'month', 'year', 'Arrival_hour', 'Arrival_minute',
       'dep_hour', 'Dep_minute', 'Duration_hour', 'Airline_Air Asia',
       'Airline_Air India', 'Airline_GoAir', 'Airline_IndiGo',
       'Airline_Jet Airways', 'Airline_Jet Airways Business',
       'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara', 'Airline_Vistara Premium economy',
       'Source_Banglore', 'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
       'Destination_Delhi', 'Destination_Hyderabad', 'Destination_Kolkata',
       'Destination_New Delhi'],
      dtype='object')

In [88]:
final_df.drop('Airline', axis=1, inplace=True)

In [89]:
final_df.drop('Source', axis=1,inplace=True)

In [90]:
final_df.drop('Destination', axis=1, inplace=True)

In [91]:
final_df

,Total_Stops,Additional_Info,Price,Date,month,year,Arrival_hour,Arrival_minute,dep_hour,Dep_minute,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,No info,3897,24,3,2019,1,10,22,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,NaN,No info,7662,1,5,2019,13,15,5,50,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,NaN,No info,13882,9,6,2019,4,25,9,25,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,No info,6218,12,5,2019,23,30,18,5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,No info,13302,1,3,2019,21,35,16,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,No info,4107,9,4,2019,22,25,19,55,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,No info,4145,27,4,2019,23,20,20,45,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,No info,7229,27,4,2019,11,20,8,20,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,No info,12648,1,3,2019,14,10,11,30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,NaN,No info,11753,9,5,2019,19,15,10,55,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [106]:
x,y = final_df.iloc[:,2],final_df.iloc[:,3:-1]

In [96]:
x

0         3897
1         7662
2        13882
3         6218
4        13302
         ...
10678     4107
10679     4145
10680     7229
10681    12648
10682    11753
Name: Price, Length: 10683, dtype: int64

In [107]:
y

,Date,month,year,Arrival_hour,Arrival_minute,dep_hour,Dep_minute,Duration_hour,Airline_Air Asia,Airline_Air India,...,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata
0,24,3,2019,1,10,22,20,2,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,5,2019,13,15,5,50,7,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,9,6,2019,4,25,9,25,19,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,12,5,2019,23,30,18,5,5,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1,3,2019,21,35,16,50,4,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9,4,2019,22,25,19,55,2,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
10679,27,4,2019,23,20,20,45,2,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
10680,27,4,2019,11,20,8,20,3,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10681,1,3,2019,14,10,11,30,2,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10682,9,5,2019,19,15,10,55,8,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [103]:
final_df['Total_Stops']

0        0.0
1        NaN
2        NaN
3        1.0
4        1.0
        ...
10678    0.0
10679    0.0
10680    0.0
10681    0.0
10682    NaN
Name: Total_Stops, Length: 10683, dtype: float64

In [111]:
x = final_df['Price']

In [112]:
x

0         3897
1         7662
2        13882
3         6218
4        13302
         ...
10678     4107
10679     4145
10680     7229
10681    12648
10682    11753
Name: Price, Length: 10683, dtype: int64

In [113]:
y = final_df.drop('Price',axis=1)

In [114]:
y

,Total_Stops,Additional_Info,Date,month,year,Arrival_hour,Arrival_minute,dep_hour,Dep_minute,Duration_hour,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,No info,24,3,2019,1,10,22,20,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,NaN,No info,1,5,2019,13,15,5,50,7,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,NaN,No info,9,6,2019,4,25,9,25,19,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,No info,12,5,2019,23,30,18,5,5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,No info,1,3,2019,21,35,16,50,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,No info,9,4,2019,22,25,19,55,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,No info,27,4,2019,23,20,20,45,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,No info,27,4,2019,11,20,8,20,3,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,No info,1,3,2019,14,10,11,30,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,NaN,No info,9,5,2019,19,15,10,55,8,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [115]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.25, random_state=1)

In [116]:
x_train

4035     2754
7865     4812
1362    15129
4236    15532
4636    13029
        ...
2895    14571
7813     4804
905      6442
5192    14151
235      4409
Name: Price, Length: 8012, dtype: int64

In [117]:
y_train

,Total_Stops,Additional_Info,Date,month,year,Arrival_hour,Arrival_minute,dep_hour,Dep_minute,Duration_hour,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
4035,0.0,No info,27,5,2019,13,30,12,0,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7865,1.0,No info,24,4,2019,13,15,8,45,4,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1362,NaN,No info,21,5,2019,19,0,13,25,29,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4236,NaN,No info,15,5,2019,13,45,16,50,20,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4636,NaN,In-flight meal not included,27,5,2019,4,25,9,40,18,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2895,1.0,No info,9,6,2019,12,0,21,10,14,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7813,0.0,No info,24,4,2019,16,55,14,25,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
905,1.0,No info,18,5,2019,16,10,8,35,7,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5192,1.0,No info,12,5,2019,9,45,9,35,24,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
235,0.0,No info,1,5,2019,12,55,10,20,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [120]:
y['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)